// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvocumahgfjpstdmfvjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2b2N1bWFoZ2ZqcHN0ZG1mdmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzM3NzQsImV4cCI6MjA3MDAwOTc3NH0.Pa-RPzGn3fJVHpqQn-i_pvPa8O5hYmg8uWcvUixN2X4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});